Sidedish 4조 백엔드 리뷰 요청드립니다.
codesquad-member-2020/sidedish-04 pull request #57
Opened 2020-05-01 09:41 UTC by guswns1659

- 조원 : 알렉스, 잭 
- 구현 기능 
  - 반찬 데이터 응답하는 API
  - Github OAuth 이용한 로그인 기능 구현 
  - JdbcTemplate 이용한 DAO 구현 
  - 외장 tomcat 활용한 war 배포

2020-05-02 10:43 UTC, wheejuni requested changes
코드 작성하시느라 수고 많으셨습니다.
다만, 기본적인 컨벤션은 늘 지켜주시기를 부탁드립니다. 

아래 코멘트 참고해 주시고요, 도움 되었으면 좋겠네요.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/domain/Badge.java
> +    private String name;
애노테이션을 사용할 땐 가독성을 위해 필드 사이에 한 줄의 공백을 만들어주세요.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/domain/Detail.java
> +    private String delivery_fee;
필드 이름에 underscore를 사용하는 것은 Python style 이고요, 
만약 JSON 필드를 위한 다른 이름이 필요했다면 `@JsonProperty` 등을 사용해 주시면 좋겠네요.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/domain/Item.java
> +    private String delivery_fee;
여기도 underscore 변수명 모두 수정해 주시고요.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/domain/MenuDAO.java
> +            public DetailDto mapRow(ResultSet rs, int rowNum) throws SQLException {
이것도 나쁘지 않지만 람다 표현식도 한 번 사용해보세요.
```java
RowMapper<DetailDto> detailMapper = (rs, rowNum) -> { 
...
```

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/service/SideDishService.java
> +        String url = "https://h3rb9c0ugl.execute-api.ap-northeast-2.amazonaws.com/develop/baminchan/" + menu + "/" + hash;
URL은 프로퍼티로 빼 주세요.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/service/SideDishService.java
> +            detailResponseDto.getData().getDetail_section().forEach(d -> detailSections.add(new DetailSection(d)));
1. `if` 문 사용할때, 실행부가 한 줄로 끝나더라도 중괄호 `{}` 빼먹지 말아 주세요.
2. `List` 객체가 null이 아니라도 원소가 없을 수도 있습니다. 
`!= null` 이 아니라 `CollectionUtils.isEmpty` 를 사용하는 게 좋고요, 
가장 좋은 건 get하지 말고 DTO 객체에게 물어보는게 제일 좋겠죠.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/controller/LoginApiController.java
> +        String redirect_url = "http://15.164.33.98/api/sidedish/github/callback";
다 properties 파일에서 관리되어야 할 정보들입니다. 
분리하는 것 고려해주세요.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/controller/LoginApiController.java
> +            String accessToken = restTemplate.postForObject(url, accessTokenRequestDto, String.class);
컨트롤러에서 다른 서비스 호출하는 코드 가급적 없었으면 좋겠습니다.
필요하다면, 이 기능을 담당할 다른 `@Component` 나 `@Service` 설계하고 구현해주세요. 

MVC 구조라는 큰 틀에서 보면, 
이 기능이 정말 Controller에 위치해야 하는지를 고민해보면 좋을 것 같습니다.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/controller/SidedishApiController.java
> +    @GetMapping("init")
데이터베이스 초기화 목적의 로직은 컨트롤러에 담지 마시고, 
별도의 `@Component` 구현하셔서 데이터베이스 INSERT하는 로직 구현하신 뒤에, 
`CommandLineRunner` 학습하신 후, 적용해보시길 권합니다.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/controller/SidedishApiController.java
> +    public String main() {
`main` 이라는 메소드명은 가급적 사용을 자제하면 좋겠습니다.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/controller/SidedishApiController.java
> +        }
이 로직은 다른 컴포넌트로 꼭 분리해주시기 바랍니다.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/dto/AccessTokenRequestDto.java
> +    private String redirect_url;
앞으로는 필드명에 **절대로 언더스코어 사용하지 말아주세요.**

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/dto/DetailDto.java
> +    @Builder
빌더의 인자로 모든 필드가 필요하다면, `@AllArgsConstructor` 를 한정적으로 선언하고 `@Builder` 를 붙여주는 방법도 있습니다. 
위 코멘트를 참고해주세요.

2020-05-02 10:43 UTC, wheejuni commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/dto/DetailDto.java
> +public class DetailDto {
아래 `@Builder` 가 모든 필드를 필요로 하기에, 아래와 같이 생성자 선언을 바꿔보는 것을 추천드려요.

```suggestion
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder
@ToString
public class DetailDto {
```

이렇게 하면, `AllArgsConstructor` 를 `private` 으로 가리고, 이 생성자에 대해 `Builder` 를 생성하는 효과를 누리게 됩니다.

2020-05-08 11:10 UTC, guswns1659 commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/service/SideDishService.java
> +        String url = "https://h3rb9c0ugl.execute-api.ap-northeast-2.amazonaws.com/develop/baminchan/" + menu + "/" + hash;
@wheejuni 프로퍼티로 뺀다는 게 속성으로 빼는 게 맞을까요?

2020-05-08 11:11 UTC, guswns1659 commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/service/SideDishService.java
> +            detailResponseDto.getData().getDetail_section().forEach(d -> detailSections.add(new DetailSection(d)));
네 감사합니다! 
질문있습니다. 
Dto 객체도 행동을 가져도 상관없나요? 단지 데이터만 전달하는 객체는 아닌건가요?

2020-05-08 11:12 UTC, guswns1659 commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/web/controller/LoginApiController.java
> +        String redirect_url = "http://15.164.33.98/api/sidedish/github/callback";
프로퍼티가 무엇인지에 대한 답을 해주신 것 같습니다! 넵

2020-05-08 11:14 UTC, guswns1659 commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/service/SideDishService.java
> +        String url = "https://h3rb9c0ugl.execute-api.ap-northeast-2.amazonaws.com/develop/baminchan/" + menu + "/" + hash;
properties 파일로 빼는 것으로 이해 완료했습니다!

2020-05-19 08:09 UTC, honux77 commented on BE/src/main/java/com/sidedish4/codesquad/sidedish/domain/MenuDAO.java
> +            public DetailDto mapRow(ResultSet rs, int rowNum) throws SQLException {
저도 람다가 더 깔끔해서 좋아요.

2020-05-19 08:15 UTC, merged